/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newView;

import com.mycompany.petshop.controller.AgendamentoCtrl;
import com.mycompany.petshop.model.classes.Agendamento;
import com.mycompany.petshop.model.classes.Funcionario;
import java.awt.CardLayout;
import java.awt.Component;
import java.sql.Time;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author viier
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    
    Funcionario logado;
    
    CardLayout layout;
    public TelaPrincipal(Funcionario logado) {
        initComponents();
        
        tableAgendamentos.getTableHeader().setFont(new java.awt.Font("Liberation Sans", 0, 18));
        tableAgendamentos.getTableHeader().setOpaque(false);
        
        
        loadTableAgendamento("hoje");
        
        layout = (CardLayout)(panelContent.getLayout());
        this.logado = logado;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        buttonInicio = new javax.swing.JButton();
        buttonFuncionarios = new javax.swing.JButton();
        buttonClientes = new javax.swing.JButton();
        buttonServicos = new javax.swing.JButton();
        buttonMercadorias = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAgendamentos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        agendamentosExibirHoje = new javax.swing.JButton();
        agendamentosExibirAmanha = new javax.swing.JButton();
        agendamentosExibirTodos = new javax.swing.JButton();
        cadastrarAgendamento = new javax.swing.JButton();
        panelFuncionarios = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        panelClientes = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        panelServicos = new javax.swing.JPanel();
        title3 = new javax.swing.JLabel();
        panelMercadorias = new javax.swing.JPanel();
        title4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(51, 51, 51));

        buttonInicio.setBackground(new java.awt.Color(51, 51, 51));
        buttonInicio.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        buttonInicio.setForeground(new java.awt.Color(255, 255, 255));
        buttonInicio.setText("Início");
        buttonInicio.setBorder(null);
        buttonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInicioActionPerformed(evt);
            }
        });

        buttonFuncionarios.setBackground(new java.awt.Color(51, 51, 51));
        buttonFuncionarios.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        buttonFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        buttonFuncionarios.setText("Funcionários");
        buttonFuncionarios.setBorder(null);
        buttonFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFuncionariosActionPerformed(evt);
            }
        });

        buttonClientes.setBackground(new java.awt.Color(51, 51, 51));
        buttonClientes.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        buttonClientes.setForeground(new java.awt.Color(255, 255, 255));
        buttonClientes.setText("Clientes");
        buttonClientes.setBorder(null);
        buttonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClientesActionPerformed(evt);
            }
        });

        buttonServicos.setBackground(new java.awt.Color(51, 51, 51));
        buttonServicos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        buttonServicos.setForeground(new java.awt.Color(255, 255, 255));
        buttonServicos.setText("Serviços");
        buttonServicos.setBorder(null);
        buttonServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonServicosActionPerformed(evt);
            }
        });

        buttonMercadorias.setBackground(new java.awt.Color(51, 51, 51));
        buttonMercadorias.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        buttonMercadorias.setForeground(new java.awt.Color(255, 255, 255));
        buttonMercadorias.setText("Mercadorias");
        buttonMercadorias.setBorder(null);
        buttonMercadorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMercadoriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonMercadorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(buttonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(buttonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMercadorias, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 620));

        panelContent.setLayout(new java.awt.CardLayout());

        title.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Início");

        tableAgendamentos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableAgendamentos.setFocusable(false);
        tableAgendamentos.setRowHeight(32);
        tableAgendamentos.setSelectionBackground(new java.awt.Color(81, 81, 81));
        tableAgendamentos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableAgendamentos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableAgendamentos);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agendamentos");

        agendamentosExibirHoje.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        agendamentosExibirHoje.setText("Exibir Hoje");
        agendamentosExibirHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendamentosExibirHojeActionPerformed(evt);
            }
        });

        agendamentosExibirAmanha.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        agendamentosExibirAmanha.setText("Exibir Amanhã");
        agendamentosExibirAmanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendamentosExibirAmanhaActionPerformed(evt);
            }
        });

        agendamentosExibirTodos.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        agendamentosExibirTodos.setText("Exibir Todos");
        agendamentosExibirTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendamentosExibirTodosActionPerformed(evt);
            }
        });

        cadastrarAgendamento.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        cadastrarAgendamento.setText("Cadastrar Novo");

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cadastrarAgendamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelInicioLayout.createSequentialGroup()
                                .addComponent(agendamentosExibirHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(agendamentosExibirAmanha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(agendamentosExibirTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agendamentosExibirAmanha, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(agendamentosExibirHoje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agendamentosExibirTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrarAgendamento, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelContent.add(panelInicio, "inicio");

        title1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Funcionários");

        javax.swing.GroupLayout panelFuncionariosLayout = new javax.swing.GroupLayout(panelFuncionarios);
        panelFuncionarios.setLayout(panelFuncionariosLayout);
        panelFuncionariosLayout.setHorizontalGroup(
            panelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelFuncionariosLayout.setVerticalGroup(
            panelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title1)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        panelContent.add(panelFuncionarios, "funcionarios");

        title2.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Clientes");

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        panelContent.add(panelClientes, "clientes");

        title3.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title3.setText("Servicos");

        javax.swing.GroupLayout panelServicosLayout = new javax.swing.GroupLayout(panelServicos);
        panelServicos.setLayout(panelServicosLayout);
        panelServicosLayout.setHorizontalGroup(
            panelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title3, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelServicosLayout.setVerticalGroup(
            panelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title3)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        panelContent.add(panelServicos, "servicos");

        title4.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        title4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title4.setText("Mercadorias");

        javax.swing.GroupLayout panelMercadoriasLayout = new javax.swing.GroupLayout(panelMercadorias);
        panelMercadorias.setLayout(panelMercadoriasLayout);
        panelMercadoriasLayout.setHorizontalGroup(
            panelMercadoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMercadoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title4, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMercadoriasLayout.setVerticalGroup(
            panelMercadoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMercadoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title4)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        panelContent.add(panelMercadorias, "mercadorias");

        getContentPane().add(panelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 950, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadTableAgendamento(String caso){
        DefaultTableModel dtm = new DefaultTableModel(new String[] {"Nome", "Serviço", "Horário"}, 0);
        
        AgendamentoCtrl fc = new AgendamentoCtrl();
        
        ArrayList<Agendamento> listaAgendamentos = fc.exibirAgendamentos(caso);

        for (Agendamento f : listaAgendamentos) {
            dtm.addRow(new Object[] {
                f.getAnimal().getNome(),
                f.getServico().getNome(),
                f.getDataHoraString()
            });
        }

        tableAgendamentos.setModel(dtm);
    }
    
    
    private void buttonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInicioActionPerformed
        // TODO add your handling code here:
        layout.show(panelContent, "inicio");
    }//GEN-LAST:event_buttonInicioActionPerformed

    private void buttonMercadoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMercadoriasActionPerformed
        // TODO add your handling code here:
        layout.show(panelContent, "mercadorias");
    }//GEN-LAST:event_buttonMercadoriasActionPerformed

    private void buttonFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFuncionariosActionPerformed
        // TODO add your handling code here:
        layout.show(panelContent, "funcionarios");
    }//GEN-LAST:event_buttonFuncionariosActionPerformed

    private void buttonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClientesActionPerformed
        // TODO add your handling code here:
        layout.show(panelContent, "clientes");
    }//GEN-LAST:event_buttonClientesActionPerformed

    private void buttonServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonServicosActionPerformed
        // TODO add your handling code here:
        layout.show(panelContent, "servicos");
    }//GEN-LAST:event_buttonServicosActionPerformed

    private void agendamentosExibirTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendamentosExibirTodosActionPerformed
        loadTableAgendamento("todos");
    }//GEN-LAST:event_agendamentosExibirTodosActionPerformed

    private void agendamentosExibirAmanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendamentosExibirAmanhaActionPerformed
        loadTableAgendamento("amanha");
    }//GEN-LAST:event_agendamentosExibirAmanhaActionPerformed

    private void agendamentosExibirHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendamentosExibirHojeActionPerformed
        loadTableAgendamento("hoje");
    }//GEN-LAST:event_agendamentosExibirHojeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Funcionario l = new Funcionario(1, "caio", Time.valueOf("08:00:00"), Time.valueOf("16:00:00"), "gerente", "abc", "123");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal(l).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendamentosExibirAmanha;
    private javax.swing.JButton agendamentosExibirHoje;
    private javax.swing.JButton agendamentosExibirTodos;
    private javax.swing.JButton buttonClientes;
    private javax.swing.JButton buttonFuncionarios;
    private javax.swing.JButton buttonInicio;
    private javax.swing.JButton buttonMercadorias;
    private javax.swing.JButton buttonServicos;
    private javax.swing.JButton cadastrarAgendamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelFuncionarios;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMercadorias;
    private javax.swing.JPanel panelServicos;
    private javax.swing.JTable tableAgendamentos;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    // End of variables declaration//GEN-END:variables
}
