/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.petshop.view;

import com.mycompany.petshop.controller.AgendamentoCtrl;
import com.mycompany.petshop.controller.ClienteCtrl;
import com.mycompany.petshop.controller.ItemCtrl;
import com.mycompany.petshop.model.classes.Agendamento;
import com.mycompany.petshop.model.classes.Animal;
import com.mycompany.petshop.model.classes.Cliente;
import com.mycompany.petshop.model.classes.Funcionario;
import com.mycompany.petshop.model.classes.Item;
import com.mycompany.petshop.model.classes.Servico;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Time;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author viier
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    
    Funcionario logado;
    
    CardLayout layout;
    
    private String caseListAgendamento;
    private int idEditandoAgendamento;
    private Agendamento anterior;
    
    void inicializarTabelas(){
        tableAgendamentos.getTableHeader().setFont(new java.awt.Font("Liberation Sans", 0, 18));
        tableSelectServicoCadastrarAgendamento.getTableHeader().setFont(new java.awt.Font("Liberation Sans", 0, 18));
        tableSelectAnimalCadastrarAgendamento.getTableHeader().setFont(new java.awt.Font("Liberation Sans", 0, 18));
        
        tableAgendamentos.getTableHeader().setOpaque(false);
        tableSelectServicoCadastrarAgendamento.getTableHeader().setOpaque(false);
        tableSelectAnimalCadastrarAgendamento.getTableHeader().setOpaque(false);
        
        tableAgendamentos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableSelectServicoCadastrarAgendamento.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableSelectAnimalCadastrarAgendamento.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    void inicializarComponentes(){
        spinnerAnoCadastrarAgendamento.setValue(LocalDate.now().getYear());
        
    }
    
    public TelaPrincipal(Funcionario logado) {
        initComponents();
        
        inicializarTabelas();
        inicializarComponentes();
        
        caseListAgendamento = "hoje";
        loadTableAgendamento(caseListAgendamento);
        
        layout = (CardLayout)(panelContent.getLayout());
        this.logado = logado;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        buttonInicio = new javax.swing.JButton();
        buttonFuncionarios = new javax.swing.JButton();
        buttonClientes = new javax.swing.JButton();
        buttonServicos = new javax.swing.JButton();
        buttonMercadorias = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAgendamentos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        agendamentosExibirHoje = new javax.swing.JButton();
        agendamentosExibirAmanha = new javax.swing.JButton();
        agendamentosExibirTodos = new javax.swing.JButton();
        buttonCadastrarAgendamento = new javax.swing.JButton();
        buttonDeletarAgendamento = new javax.swing.JButton();
        buttonEditarAgendamento = new javax.swing.JButton();
        panelCadastrarAgendamento = new javax.swing.JPanel();
        title5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSelectServicoCadastrarAgendamento = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableSelectAnimalCadastrarAgendamento = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textPesquisaCpfCadastrarAgendamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        spinnerDiaCadastrarAgendamento = new javax.swing.JSpinner(new SpinnerNumberModel(1, 1, 31, 1));
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinnerMesCadastrarAgendamento = new javax.swing.JSpinner(new SpinnerNumberModel(1, 1, 12, 1));
        jLabel9 = new javax.swing.JLabel();
        spinnerAnoCadastrarAgendamento = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        spinnerHoraCadastrarAgendamento = new javax.swing.JSpinner(new SpinnerNumberModel(0, 0, 31, 1));
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        spinnerMinutoCadastrarAgendamento = new javax.swing.JSpinner(new SpinnerNumberModel(0, 0, 59, 15));
        buttonEfetuarCadastroAgendamento = new javax.swing.JButton();
        buttonCancelarCadastroAgendamento = new javax.swing.JButton();
        panelEditarAgendamento = new javax.swing.JPanel();
        title6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableSelectServicoEditarAgendamento = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableSelectAnimalEditarAgendamento = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textPesquisaCpfEditarAgendamento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        spinnerDiaEditarAgendamento = new javax.swing.JSpinner(new SpinnerNumberModel(1, 1, 31, 1));
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        spinnerMesEditarAgendamento = new javax.swing.JSpinner(new SpinnerNumberModel(1, 1, 12, 1));
        jLabel20 = new javax.swing.JLabel();
        spinnerAnoEditarAgendamento = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        spinnerHoraEditarAgendamento = new javax.swing.JSpinner(new SpinnerNumberModel(1, 1, 31, 1));
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        spinnerMinutoEditarAgendamento = new javax.swing.JSpinner(new SpinnerNumberModel(0, 0, 59, 15));
        buttonEfetuarEditarAgendamento = new javax.swing.JButton();
        buttonCancelarEditarAgendamento = new javax.swing.JButton();
        panelFuncionarios = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        panelClientes = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        panelServicos = new javax.swing.JPanel();
        title3 = new javax.swing.JLabel();
        panelMercadorias = new javax.swing.JPanel();
        title4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(51, 51, 51));

        buttonInicio.setBackground(new java.awt.Color(51, 51, 51));
        buttonInicio.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        buttonInicio.setForeground(new java.awt.Color(255, 255, 255));
        buttonInicio.setText("Início");
        buttonInicio.setBorder(null);
        buttonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInicioActionPerformed(evt);
            }
        });

        buttonFuncionarios.setBackground(new java.awt.Color(51, 51, 51));
        buttonFuncionarios.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        buttonFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        buttonFuncionarios.setText("Funcionários");
        buttonFuncionarios.setBorder(null);
        buttonFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFuncionariosActionPerformed(evt);
            }
        });

        buttonClientes.setBackground(new java.awt.Color(51, 51, 51));
        buttonClientes.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        buttonClientes.setForeground(new java.awt.Color(255, 255, 255));
        buttonClientes.setText("Clientes");
        buttonClientes.setBorder(null);
        buttonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClientesActionPerformed(evt);
            }
        });

        buttonServicos.setBackground(new java.awt.Color(51, 51, 51));
        buttonServicos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        buttonServicos.setForeground(new java.awt.Color(255, 255, 255));
        buttonServicos.setText("Serviços");
        buttonServicos.setBorder(null);
        buttonServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonServicosActionPerformed(evt);
            }
        });

        buttonMercadorias.setBackground(new java.awt.Color(51, 51, 51));
        buttonMercadorias.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        buttonMercadorias.setForeground(new java.awt.Color(255, 255, 255));
        buttonMercadorias.setText("Mercadorias");
        buttonMercadorias.setBorder(null);
        buttonMercadorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMercadoriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonMercadorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(buttonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(buttonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMercadorias, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 620));

        panelContent.setLayout(new java.awt.CardLayout());

        title.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Início");

        tableAgendamentos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableAgendamentos.setFocusable(false);
        tableAgendamentos.setRowHeight(32);
        tableAgendamentos.setSelectionBackground(new java.awt.Color(81, 81, 81));
        tableAgendamentos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableAgendamentos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableAgendamentos);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agendamentos");

        agendamentosExibirHoje.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        agendamentosExibirHoje.setText("Exibir Hoje");
        agendamentosExibirHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendamentosExibirHojeActionPerformed(evt);
            }
        });

        agendamentosExibirAmanha.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        agendamentosExibirAmanha.setText("Exibir Amanhã");
        agendamentosExibirAmanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendamentosExibirAmanhaActionPerformed(evt);
            }
        });

        agendamentosExibirTodos.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        agendamentosExibirTodos.setText("Exibir Todos");
        agendamentosExibirTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendamentosExibirTodosActionPerformed(evt);
            }
        });

        buttonCadastrarAgendamento.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        buttonCadastrarAgendamento.setText("Cadastrar Novo");
        buttonCadastrarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarAgendamentoActionPerformed(evt);
            }
        });

        buttonDeletarAgendamento.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        buttonDeletarAgendamento.setForeground(new java.awt.Color(197, 0, 0));
        buttonDeletarAgendamento.setText("Deletar");
        buttonDeletarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletarAgendamentoActionPerformed(evt);
            }
        });

        buttonEditarAgendamento.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        buttonEditarAgendamento.setText("Editar");
        buttonEditarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarAgendamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInicioLayout.createSequentialGroup()
                                .addComponent(agendamentosExibirHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(agendamentosExibirAmanha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonCadastrarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(agendamentosExibirTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(buttonEditarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDeletarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agendamentosExibirAmanha, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(agendamentosExibirHoje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agendamentosExibirTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonEditarAgendamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDeletarAgendamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCadastrarAgendamento, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelContent.add(panelInicio, "inicio");

        title5.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        title5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title5.setText("Início");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastrar novo Agendamento");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Selecione o Serviço");

        tableSelectServicoCadastrarAgendamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tableSelectServicoCadastrarAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSelectServicoCadastrarAgendamento.setRowHeight(40);
        tableSelectServicoCadastrarAgendamento.getTableHeader().setResizingAllowed(false);
        tableSelectServicoCadastrarAgendamento.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tableSelectServicoCadastrarAgendamento);
        if (tableSelectServicoCadastrarAgendamento.getColumnModel().getColumnCount() > 0) {
            tableSelectServicoCadastrarAgendamento.getColumnModel().getColumn(0).setMinWidth(40);
            tableSelectServicoCadastrarAgendamento.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableSelectServicoCadastrarAgendamento.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        tableSelectAnimalCadastrarAgendamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tableSelectAnimalCadastrarAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSelectAnimalCadastrarAgendamento.setRowHeight(40);
        tableSelectAnimalCadastrarAgendamento.getTableHeader().setResizingAllowed(false);
        tableSelectAnimalCadastrarAgendamento.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tableSelectAnimalCadastrarAgendamento);
        if (tableSelectAnimalCadastrarAgendamento.getColumnModel().getColumnCount() > 0) {
            tableSelectAnimalCadastrarAgendamento.getColumnModel().getColumn(0).setMinWidth(40);
            tableSelectAnimalCadastrarAgendamento.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableSelectAnimalCadastrarAgendamento.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Selecione o Animal");

        jLabel5.setText("Buscar pelo CPF do dono:");

        textPesquisaCpfCadastrarAgendamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPesquisaCpfCadastrarAgendamentoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Selecione a Data");

        spinnerDiaCadastrarAgendamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Dia:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Mês:");

        spinnerMesCadastrarAgendamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ano:");

        spinnerAnoCadastrarAgendamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Selecione a Hora");

        spinnerHoraCadastrarAgendamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Hora:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Minuto:");

        spinnerMinutoCadastrarAgendamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        buttonEfetuarCadastroAgendamento.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        buttonEfetuarCadastroAgendamento.setForeground(new java.awt.Color(0, 153, 51));
        buttonEfetuarCadastroAgendamento.setText("Cadastrar");
        buttonEfetuarCadastroAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEfetuarCadastroAgendamentoActionPerformed(evt);
            }
        });

        buttonCancelarCadastroAgendamento.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        buttonCancelarCadastroAgendamento.setForeground(new java.awt.Color(153, 0, 51));
        buttonCancelarCadastroAgendamento.setText("Cancelar");
        buttonCancelarCadastroAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarCadastroAgendamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCadastrarAgendamentoLayout = new javax.swing.GroupLayout(panelCadastrarAgendamento);
        panelCadastrarAgendamento.setLayout(panelCadastrarAgendamentoLayout);
        panelCadastrarAgendamentoLayout.setHorizontalGroup(
            panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarAgendamentoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(textPesquisaCpfCadastrarAgendamento)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCadastrarAgendamentoLayout.createSequentialGroup()
                        .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinnerDiaCadastrarAgendamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinnerMesCadastrarAgendamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinnerAnoCadastrarAgendamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCadastrarAgendamentoLayout.createSequentialGroup()
                        .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCadastrarAgendamentoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(spinnerHoraCadastrarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinnerMinutoCadastrarAgendamento))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelCadastrarAgendamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarAgendamentoLayout.createSequentialGroup()
                        .addComponent(buttonCancelarCadastroAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonEfetuarCadastroAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCadastrarAgendamentoLayout.setVerticalGroup(
            panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarAgendamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastrarAgendamentoLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadastrarAgendamentoLayout.createSequentialGroup()
                        .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCadastrarAgendamentoLayout.createSequentialGroup()
                                .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelCadastrarAgendamentoLayout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(spinnerAnoCadastrarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelCadastrarAgendamentoLayout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(spinnerMesCadastrarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(spinnerDiaCadastrarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(57, 57, 57)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spinnerHoraCadastrarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerMinutoCadastrarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastrarAgendamentoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPesquisaCpfCadastrarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarAgendamentoLayout.createSequentialGroup()
                        .addGap(0, 139, Short.MAX_VALUE)
                        .addGroup(panelCadastrarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCancelarCadastroAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonEfetuarCadastroAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        panelContent.add(panelCadastrarAgendamento, "cadastrarAgendamento");

        title6.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        title6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title6.setText("Início");

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Editar Agendamento");

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Selecione o Serviço");

        tableSelectServicoEditarAgendamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tableSelectServicoEditarAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSelectServicoEditarAgendamento.setRowHeight(40);
        tableSelectServicoEditarAgendamento.getTableHeader().setResizingAllowed(false);
        tableSelectServicoEditarAgendamento.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tableSelectServicoEditarAgendamento);
        if (tableSelectServicoEditarAgendamento.getColumnModel().getColumnCount() > 0) {
            tableSelectServicoEditarAgendamento.getColumnModel().getColumn(0).setMinWidth(40);
            tableSelectServicoEditarAgendamento.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableSelectServicoEditarAgendamento.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        tableSelectAnimalEditarAgendamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tableSelectAnimalEditarAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSelectAnimalEditarAgendamento.setRowHeight(40);
        tableSelectAnimalEditarAgendamento.getTableHeader().setResizingAllowed(false);
        tableSelectAnimalEditarAgendamento.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tableSelectAnimalEditarAgendamento);
        if (tableSelectAnimalEditarAgendamento.getColumnModel().getColumnCount() > 0) {
            tableSelectAnimalEditarAgendamento.getColumnModel().getColumn(0).setMinWidth(40);
            tableSelectAnimalEditarAgendamento.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableSelectAnimalEditarAgendamento.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Selecione o Animal");

        jLabel16.setText("Buscar pelo CPF do dono:");

        textPesquisaCpfEditarAgendamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPesquisaCpfEditarAgendamentoKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Selecione a Data");

        spinnerDiaEditarAgendamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Dia:");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Mês:");

        spinnerMesEditarAgendamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Ano:");

        spinnerAnoEditarAgendamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Selecione a Hora");

        spinnerHoraEditarAgendamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Hora:");

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Minuto:");

        spinnerMinutoEditarAgendamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        buttonEfetuarEditarAgendamento.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        buttonEfetuarEditarAgendamento.setForeground(new java.awt.Color(0, 153, 51));
        buttonEfetuarEditarAgendamento.setText("Salvar");
        buttonEfetuarEditarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEfetuarEditarAgendamentoActionPerformed(evt);
            }
        });

        buttonCancelarEditarAgendamento.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        buttonCancelarEditarAgendamento.setForeground(new java.awt.Color(153, 0, 51));
        buttonCancelarEditarAgendamento.setText("Cancelar");
        buttonCancelarEditarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarEditarAgendamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditarAgendamentoLayout = new javax.swing.GroupLayout(panelEditarAgendamento);
        panelEditarAgendamento.setLayout(panelEditarAgendamentoLayout);
        panelEditarAgendamentoLayout.setHorizontalGroup(
            panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarAgendamentoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(textPesquisaCpfEditarAgendamento)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEditarAgendamentoLayout.createSequentialGroup()
                        .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinnerDiaEditarAgendamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinnerMesEditarAgendamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinnerAnoEditarAgendamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelEditarAgendamentoLayout.createSequentialGroup()
                        .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelEditarAgendamentoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(spinnerHoraEditarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinnerMinutoEditarAgendamento))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelEditarAgendamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditarAgendamentoLayout.createSequentialGroup()
                        .addComponent(buttonCancelarEditarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonEfetuarEditarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelEditarAgendamentoLayout.setVerticalGroup(
            panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarAgendamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditarAgendamentoLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEditarAgendamentoLayout.createSequentialGroup()
                        .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelEditarAgendamentoLayout.createSequentialGroup()
                                .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelEditarAgendamentoLayout.createSequentialGroup()
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(spinnerAnoEditarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelEditarAgendamentoLayout.createSequentialGroup()
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(spinnerMesEditarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(spinnerDiaEditarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(57, 57, 57)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spinnerHoraEditarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerMinutoEditarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditarAgendamentoLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPesquisaCpfEditarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditarAgendamentoLayout.createSequentialGroup()
                        .addGap(0, 139, Short.MAX_VALUE)
                        .addGroup(panelEditarAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCancelarEditarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonEfetuarEditarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        panelContent.add(panelEditarAgendamento, "editarAgendamento");

        title1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Funcionários");

        javax.swing.GroupLayout panelFuncionariosLayout = new javax.swing.GroupLayout(panelFuncionarios);
        panelFuncionarios.setLayout(panelFuncionariosLayout);
        panelFuncionariosLayout.setHorizontalGroup(
            panelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelFuncionariosLayout.setVerticalGroup(
            panelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title1)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        panelContent.add(panelFuncionarios, "funcionarios");

        title2.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Clientes");

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        panelContent.add(panelClientes, "clientes");

        title3.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title3.setText("Servicos");

        javax.swing.GroupLayout panelServicosLayout = new javax.swing.GroupLayout(panelServicos);
        panelServicos.setLayout(panelServicosLayout);
        panelServicosLayout.setHorizontalGroup(
            panelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title3, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelServicosLayout.setVerticalGroup(
            panelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title3)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        panelContent.add(panelServicos, "servicos");

        title4.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        title4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title4.setText("Mercadorias");

        javax.swing.GroupLayout panelMercadoriasLayout = new javax.swing.GroupLayout(panelMercadorias);
        panelMercadorias.setLayout(panelMercadoriasLayout);
        panelMercadoriasLayout.setHorizontalGroup(
            panelMercadoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMercadoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title4, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMercadoriasLayout.setVerticalGroup(
            panelMercadoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMercadoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title4)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        panelContent.add(panelMercadorias, "mercadorias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        panelContent.add(jPanel1, "card9");

        getContentPane().add(panelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 950, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadTableAgendamento(String caso){
        DefaultTableModel dtm = new DefaultTableModel(new String[] {"ID","Nome", "Serviço", "Horário"}, 0);
        
        AgendamentoCtrl fc = new AgendamentoCtrl();
        
        ArrayList<Agendamento> listaAgendamentos = fc.exibirAgendamentos(caso);

        for (Agendamento f : listaAgendamentos) {
            dtm.addRow(new Object[] {
                f.getId(),
                f.getAnimal().getNome(),
                f.getServico().getNome(),
                f.getDataHoraString()
            });
        }
        
        tableAgendamentos.setModel(dtm);
    }
    
    private void loadTableServico(JTable table){
        DefaultTableModel dtm = new DefaultTableModel(new String[] {"ID","Nome"}, 0);
        
        ItemCtrl ic = new ItemCtrl();
        
        ArrayList<Item> lista = ic.exibirServicos();

        for (Item f : lista) {
            dtm.addRow(new Object[] {
                f.getId(),
                f.getNome()
            });
        }
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table.setModel(dtm);
        table.getColumnModel().getColumn(0).setPreferredWidth(40);
        table.getColumnModel().getColumn(0).setMinWidth(40);
        table.getColumnModel().getColumn(0).setMaxWidth(40);
    }
    
    private void loadTableAnimal(JTable table, String cpfDono){
        DefaultTableModel dtm = new DefaultTableModel(new String[] {"ID","Nome"}, 0);
        
        ClienteCtrl cc = new ClienteCtrl();
        
        ArrayList<Cliente> lista = cc.exibirAnimais(cpfDono);

        for (Cliente f : lista) {
            dtm.addRow(new Object[] {
                f.getId(),
                f.getNome()
            });
        }
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table.setModel(dtm);
        table.getColumnModel().getColumn(0).setPreferredWidth(40);
        table.getColumnModel().getColumn(0).setMinWidth(40);
        table.getColumnModel().getColumn(0).setMaxWidth(40);
    }
    
    
    private void buttonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInicioActionPerformed
        // TODO add your handling code here:
        layout.show(panelContent, "inicio");
    }//GEN-LAST:event_buttonInicioActionPerformed

    private void buttonMercadoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMercadoriasActionPerformed
        // TODO add your handling code here:
        layout.show(panelContent, "mercadorias");
    }//GEN-LAST:event_buttonMercadoriasActionPerformed

    private void buttonFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFuncionariosActionPerformed
        // TODO add your handling code here:
        layout.show(panelContent, "funcionarios");
    }//GEN-LAST:event_buttonFuncionariosActionPerformed

    private void buttonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClientesActionPerformed
        // TODO add your handling code here:
        layout.show(panelContent, "clientes");
    }//GEN-LAST:event_buttonClientesActionPerformed

    private void buttonServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonServicosActionPerformed
        // TODO add your handling code here:
        layout.show(panelContent, "servicos");
    }//GEN-LAST:event_buttonServicosActionPerformed

    private void agendamentosExibirTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendamentosExibirTodosActionPerformed
        caseListAgendamento = "todos";
        loadTableAgendamento(caseListAgendamento);
    }//GEN-LAST:event_agendamentosExibirTodosActionPerformed

    private void agendamentosExibirAmanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendamentosExibirAmanhaActionPerformed
        caseListAgendamento = "amanha";
        loadTableAgendamento(caseListAgendamento);
    }//GEN-LAST:event_agendamentosExibirAmanhaActionPerformed

    private void agendamentosExibirHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendamentosExibirHojeActionPerformed
        caseListAgendamento = "hoje";
        loadTableAgendamento(caseListAgendamento);
    }//GEN-LAST:event_agendamentosExibirHojeActionPerformed

    private void buttonDeletarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeletarAgendamentoActionPerformed
        AgendamentoCtrl ac = new AgendamentoCtrl();

        int linhaSelecionada = tableAgendamentos.getSelectedRow();
        if (linhaSelecionada != -1) {
            DefaultTableModel model = (DefaultTableModel) tableAgendamentos.getModel();
            int id = (Integer) model.getValueAt(linhaSelecionada, 0); 
            ac.excluir(id);
            loadTableAgendamento(caseListAgendamento);
        }
        
    }//GEN-LAST:event_buttonDeletarAgendamentoActionPerformed

    private void buttonEditarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarAgendamentoActionPerformed
        int linhaSelecionada = tableAgendamentos.getSelectedRow();
        int id = 0;
        if (linhaSelecionada != -1) {
            DefaultTableModel model = (DefaultTableModel) tableAgendamentos.getModel();
            id = (Integer) model.getValueAt(linhaSelecionada, 0);
            
            AgendamentoCtrl ac = new AgendamentoCtrl();
        
            this.anterior = ac.exibirAgendamentoById(id);
            
            //popula data
            spinnerAnoEditarAgendamento.setValue(anterior.getData_hora().getYear());
            spinnerMesEditarAgendamento.setValue(anterior.getData_hora().getMonth());
            spinnerDiaEditarAgendamento.setValue(anterior.getData_hora().getDate());
            spinnerHoraEditarAgendamento.setValue(anterior.getData_hora().getHours());
            spinnerMinutoEditarAgendamento.setValue(anterior.getData_hora().getMinutes());

            // carrega tabelas atualizadas
            loadTableServico(tableSelectServicoEditarAgendamento);
            loadTableAnimal(tableSelectAnimalEditarAgendamento, textPesquisaCpfEditarAgendamento.getText());

            // seleciona na tabela o animal p editar
            TableModel animal = tableSelectAnimalEditarAgendamento.getModel();
            int idLinhaSelecionada = 0, nLinhaSelecionada = 0;
            for(int i = 0; i < animal.getColumnCount(); i++){
                idLinhaSelecionada = (Integer) animal.getValueAt(i, 0);
                nLinhaSelecionada = i;
                if(this.anterior.getAnimal().getId() == idLinhaSelecionada) break; 
            }
            tableSelectAnimalEditarAgendamento.getSelectionModel().setSelectionInterval(nLinhaSelecionada, nLinhaSelecionada);
            
            // seleciona ma tabela o servico p editar
            TableModel servico = tableSelectServicoEditarAgendamento.getModel();
            idLinhaSelecionada = 0; 
            nLinhaSelecionada = 0;
            for(int i = 0; i < servico.getColumnCount(); i++){
                idLinhaSelecionada = (Integer) servico.getValueAt(i, 0);
                nLinhaSelecionada = i;
                if(anterior.getServico().getId() == idLinhaSelecionada) break; 
            }
            tableSelectServicoEditarAgendamento.getSelectionModel().setSelectionInterval(nLinhaSelecionada, nLinhaSelecionada);

            layout.show(panelContent, "editarAgendamento");

        }
        
        
    }//GEN-LAST:event_buttonEditarAgendamentoActionPerformed

    private void buttonCadastrarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarAgendamentoActionPerformed
        loadTableServico(tableSelectServicoCadastrarAgendamento);
        loadTableAnimal(tableSelectAnimalCadastrarAgendamento, textPesquisaCpfCadastrarAgendamento.getText());
        layout.show(panelContent, "cadastrarAgendamento");
        
    }//GEN-LAST:event_buttonCadastrarAgendamentoActionPerformed

    private void textPesquisaCpfCadastrarAgendamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPesquisaCpfCadastrarAgendamentoKeyTyped
        loadTableAnimal(tableSelectAnimalCadastrarAgendamento ,textPesquisaCpfCadastrarAgendamento.getText());
        
    }//GEN-LAST:event_textPesquisaCpfCadastrarAgendamentoKeyTyped

    private void buttonEfetuarCadastroAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEfetuarCadastroAgendamentoActionPerformed
        
        Timestamp data_hora = new Timestamp((Integer) spinnerAnoCadastrarAgendamento.getValue(), (Integer) spinnerMesCadastrarAgendamento.getValue(), (Integer) spinnerDiaCadastrarAgendamento.getValue(), (Integer) spinnerHoraCadastrarAgendamento.getValue(), (Integer) spinnerMinutoCadastrarAgendamento.getValue(), 0, 0);

        int animal = 0, servico = 0;
        
        
        int linhaSelecionadaAnimal = tableSelectAnimalCadastrarAgendamento.getSelectedRow();
        if (linhaSelecionadaAnimal != -1) {
            DefaultTableModel model = (DefaultTableModel) tableSelectAnimalCadastrarAgendamento.getModel();
            animal = (Integer) model.getValueAt(linhaSelecionadaAnimal, 0);
        }
        
        int linhaSelecionadaServico = tableSelectServicoCadastrarAgendamento.getSelectedRow();
        if (linhaSelecionadaServico != -1) {
            DefaultTableModel model = (DefaultTableModel) tableSelectServicoCadastrarAgendamento.getModel();
            
            servico = (Integer) model.getValueAt(linhaSelecionadaServico, 0);
            System.out.println(servico);
        }
        
        if(animal != 0 && servico != 0){
            AgendamentoCtrl ac = new AgendamentoCtrl();
            ac.cadastrarAgendamento(0, data_hora, new Animal(animal), new Servico(servico));
        }else{
            JOptionPane.showMessageDialog(null, "Algo não estava correto, tente novamente.");
        }
        
        
        loadTableAgendamento(caseListAgendamento);
        layout.show(panelContent, "inicio");
    }//GEN-LAST:event_buttonEfetuarCadastroAgendamentoActionPerformed

    private void buttonCancelarCadastroAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarCadastroAgendamentoActionPerformed
        layout.show(panelContent, "inicio");
    }//GEN-LAST:event_buttonCancelarCadastroAgendamentoActionPerformed

    private void textPesquisaCpfEditarAgendamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPesquisaCpfEditarAgendamentoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textPesquisaCpfEditarAgendamentoKeyTyped

    private void buttonEfetuarEditarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEfetuarEditarAgendamentoActionPerformed
        Timestamp data_hora = new Timestamp((Integer) spinnerAnoEditarAgendamento.getValue(), (Integer) spinnerMesEditarAgendamento.getValue(), (Integer) spinnerDiaEditarAgendamento.getValue(), (Integer) spinnerHoraEditarAgendamento.getValue(), (Integer) spinnerMinutoEditarAgendamento.getValue(), 0, 0);
        
//        String s = "";
//        s = (String.format("%02d", data_hora.getDate()) + "/" + String.format("%02d", data_hora.getMonth())+ "/" + data_hora.getYear() + " " + data_hora.getHours()+ ":"+String.format("%02d", data_hora.getMinutes()));
//        System.out.println(s);
        
        int animal = 0, servico = 0;
        
        
        
        int linhaSelecionadaAnimal = tableSelectAnimalCadastrarAgendamento.getSelectedRow();
        if (linhaSelecionadaAnimal != -1) {
            DefaultTableModel model = (DefaultTableModel) tableSelectAnimalCadastrarAgendamento.getModel();
            animal = (Integer) model.getValueAt(linhaSelecionadaAnimal, 0);
        }else{
            animal = this.anterior.getAnimal().getId();
        }
        
        int linhaSelecionadaServico = tableSelectServicoCadastrarAgendamento.getSelectedRow();
        if (linhaSelecionadaServico != -1) {
            DefaultTableModel model = (DefaultTableModel) tableSelectServicoCadastrarAgendamento.getModel();
            
            servico = (Integer) model.getValueAt(linhaSelecionadaServico, 0);
            System.out.println(servico);
        }else{
            servico = this.anterior.getServico().getId();
        }
        
        System.out.println(this.anterior);
        System.out.println("Animal: " + animal);
        System.out.println("Servico: " + servico);
        
        if(animal != 0 && servico != 0){
            AgendamentoCtrl ac = new AgendamentoCtrl();
            ac.atualizarAgendamento(this.anterior.getId(), data_hora, new Animal(animal), new Servico(servico));
        }else{
            JOptionPane.showMessageDialog(null, "Algo não estava correto, tente novamente.");
        }
        
        
        loadTableAgendamento(caseListAgendamento);
        layout.show(panelContent, "inicio");
    }//GEN-LAST:event_buttonEfetuarEditarAgendamentoActionPerformed

    private void buttonCancelarEditarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarEditarAgendamentoActionPerformed
        layout.show(panelContent, "inicio");
    }//GEN-LAST:event_buttonCancelarEditarAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Funcionario l = new Funcionario(1, "caio", Time.valueOf("08:00:00"), Time.valueOf("16:00:00"), "gerente", "abc", "123");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal(l).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendamentosExibirAmanha;
    private javax.swing.JButton agendamentosExibirHoje;
    private javax.swing.JButton agendamentosExibirTodos;
    private javax.swing.JButton buttonCadastrarAgendamento;
    private javax.swing.JButton buttonCancelarCadastroAgendamento;
    private javax.swing.JButton buttonCancelarEditarAgendamento;
    private javax.swing.JButton buttonClientes;
    private javax.swing.JButton buttonDeletarAgendamento;
    private javax.swing.JButton buttonEditarAgendamento;
    private javax.swing.JButton buttonEfetuarCadastroAgendamento;
    private javax.swing.JButton buttonEfetuarEditarAgendamento;
    private javax.swing.JButton buttonFuncionarios;
    private javax.swing.JButton buttonInicio;
    private javax.swing.JButton buttonMercadorias;
    private javax.swing.JButton buttonServicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel panelCadastrarAgendamento;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelEditarAgendamento;
    private javax.swing.JPanel panelFuncionarios;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMercadorias;
    private javax.swing.JPanel panelServicos;
    private javax.swing.JSpinner spinnerAnoCadastrarAgendamento;
    private javax.swing.JSpinner spinnerAnoEditarAgendamento;
    private javax.swing.JSpinner spinnerDiaCadastrarAgendamento;
    private javax.swing.JSpinner spinnerDiaEditarAgendamento;
    private javax.swing.JSpinner spinnerHoraCadastrarAgendamento;
    private javax.swing.JSpinner spinnerHoraEditarAgendamento;
    private javax.swing.JSpinner spinnerMesCadastrarAgendamento;
    private javax.swing.JSpinner spinnerMesEditarAgendamento;
    private javax.swing.JSpinner spinnerMinutoCadastrarAgendamento;
    private javax.swing.JSpinner spinnerMinutoEditarAgendamento;
    private javax.swing.JTable tableAgendamentos;
    private javax.swing.JTable tableSelectAnimalCadastrarAgendamento;
    private javax.swing.JTable tableSelectAnimalEditarAgendamento;
    private javax.swing.JTable tableSelectServicoCadastrarAgendamento;
    private javax.swing.JTable tableSelectServicoEditarAgendamento;
    private javax.swing.JTextField textPesquisaCpfCadastrarAgendamento;
    private javax.swing.JTextField textPesquisaCpfEditarAgendamento;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    // End of variables declaration//GEN-END:variables
}
